CREATE TABLE song (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	artist TEXT NOT NULL,
	cover TEXT NOT NULL,
	rank INTEGER
);

CREATE TABLE tag (
	id SERIAL PRIMARY KEY,
	song_id INTEGER REFERENCES song(id) ON DELETE CASCADE,
	name TEXT NOT NULL
);

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL UNIQUE CHECK(LENGTH(name) > 0),
	password TEXT NOT NULL CHECK(LENGTH(password) > 7)
);

CREATE TABLE favorite (
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	song_id INTEGER NOT NULL REFERENCES song(id) ON DELETE CASCADE,
	PRIMARY KEY (user_id, song_id)
);