type Query {
	top100: [Song!]!
	myFavorites: [Song!]!
}

type Mutation {
	signup(name: String!, password: String!): User!
	login(name: String!, password: String!): User!

	favorite(songId: Int!, isFavorite: Boolean!): Song!
}

type Song {
	title: String!
	artist: String!
	cover: String!
	genre: String!
	ranking: Int!
	isFavorite: Boolean!
}

type User {
	id: Int!
	name: String!
}