type Query {
	top100: [Song!]!
	user(id: Int): User!
}

type Mutation {
	signup(name: String!, password: String!): User!
	login(name: String!, password: String!): User!
	logout: Boolean!

	favorite(songId: Int!, isFavorite: Boolean!): Song!
}

type Song {
	id: Int!
	title: String!
	artist: String!
	cover: String!
	tag: String!
	rank: Int!
	isFavorite: Boolean!
}

type User {
	id: Int!
	name: String!
	favorites: [Song!]!
}